In [33]:
import pandas as pd
import re

In [2]:
path='C:/Github_clones/creating_datset_by_web-scraping/Disney_movies.csv'

In [3]:
data = pd.read_csv(path) 
data.head()

,Unnamed: 0,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget,Box_office
0,0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 million,$418 million
1,1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 million,$164 million
2,2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 million,$76.4–$83.3 million (United States and Canada)
3,3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000 (worldwide rentals)"
4,4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",>$1.3 million (est. United States/Canada renta...

In [9]:
data.drop("Unnamed: 0",inplace=True, axis=1)

In [10]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget,Box_office
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 million,$418 million
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 million,$164 million
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 million,$76.4–$83.3 million (United States and Canada)
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000 (worldwide rentals)"
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",>$1.3 million (est. United States/Canada renta...

In [12]:
data.isnull().sum()

Movie_name            0
Movie_release_date    5
Wikipedia_link        0
Running_time          0
Budget                2
Box_office            3
dtype: int64

In [13]:
data.fillna("N/A", inplace = True)

In [14]:
data.isnull().sum()

Movie_name            0
Movie_release_date    0
Wikipedia_link        0
Running_time          0
Budget                0
Box_office            0
dtype: int64

In [15]:
data.columns

Index(['Movie_name', 'Movie_release_date', 'Wikipedia_link', 'Running_time',
       'Budget', 'Box_office'],
      dtype='object')

In [19]:
print(type(data["Running_time"]))

<class 'pandas.core.series.Series'>

In [29]:
data["Running_time(in minutes)"]= data["Running_time"].str.replace('min',"")
data["Running_time(in minutes)"]= data["Running_time(in minutes)"].str.replace('utes',"")

In [30]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget,Box_office,Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 million,$418 million,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 million,$164 million,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 million,$76.4–$83.3 million (United States and Canada),126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000 (worldwide rentals)",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",>$1.3 million (est. United States/Canada renta...,64

In [31]:
data["Box_office"]= data["Box_office"].str.replace('million',"M")
data["Box_office"]= data["Box_office"].str.replace('',"M")

In [32]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget,Box_office,Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 million,$418 M,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 million,$164 M,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 million,$76.4–$83.3 M (United States and Canada),126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000 (worldwide rentals)",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",">$1.3 M (est. United States/Canada rentals, 1941)",64

In [34]:
clutter_one = re.compile(r'\(.*\)$')
data["Box_office"]= data["Box_office"].str.replace(clutter_one,"")

In [35]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget,Box_office,Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 million,$418 M,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 million,$164 M,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 million,$76.4–$83.3 M,126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",>$1.3 M,64

In [36]:
data["Budget"]= data["Budget"].str.replace("million","M")

In [37]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget,Box_office,Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 M,$418 M,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 M,$164 M,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 M,$76.4–$83.3 M,126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",>$1.3 M,64

In [39]:
data.rename(columns = {'Budget':'Budget(USD)','Box_office':'Box_office(USD)'}, inplace = True)

In [40]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget(USD),Box_office(USD),Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,$1.49 M,$418 M,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,$2.6 M,$164 M,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,$2.28 M,$76.4–$83.3 M,126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"$600,000","$960,000",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"$950,000",>$1.3 M,64

In [41]:
data["Budget(USD)"]= data["Budget(USD)"].str.replace("$","")
data["Box_office(USD)"]= data["Box_office(USD)"].str.replace("$","")

<ipython-input-41-bf165f2947cf>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  data["Budget(USD)"]= data["Budget(USD)"].str.replace("$","")
<ipython-input-41-bf165f2947cf>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  data["Box_office(USD)"]= data["Box_office(USD)"].str.replace("$","")

In [42]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Running_time,Budget(USD),Box_office(USD),Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,83 minutes,1.49 M,418 M,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,88 minutes,2.6 M,164 M,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,126 minutes,2.28 M,76.4–83.3 M,126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,74 minutes,"600,000","960,000",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,64 minutes,"950,000",>1.3 M,64

In [43]:
data["Box_office(USD)"]= data["Box_office(USD)"].str.replace(">","")

In [45]:
data["Running_time(in minutes)"]= data["Running_time(in minutes)"].str.replace(clutter_one,"")

In [54]:
data["Box_office(USD)"]= data["Box_office(USD)"].str.replace(clutter_one,"")
data["Budget(USD)"]= data["Budget(USD)"].str.replace(clutter_one,"")

In [56]:
data.loc[187,:]

Movie_name                                                         G-Force
Movie_release_date                                           July 24, 2009
Wikipedia_link              https://en.m.wikipedia.org/wiki/G-Force_(film)
Running_time                                                    90 minutes
Budget(USD)                                                          150 M
Box_office(USD)                                                    292.8 M
Running_time(in minutes)                                               90
Name: 187, dtype: object

In [57]:
data.drop("Running_time",inplace=True, axis=1)

In [58]:
data.head()

,Movie_name,Movie_release_date,Wikipedia_link,Budget(USD),Box_office(USD),Running_time(in minutes)
0,Snow White and the Seven Dwarfs,"December 21, 1937",https://en.m.wikipedia.org/wiki/Snow_White_and...,1.49 M,418 M,83
1,Pinocchio,"February 7, 1940",https://en.m.wikipedia.org/wiki/Pinocchio_(194...,2.6 M,164 M,88
2,Fantasia,"November 13, 1940",https://en.m.wikipedia.org/wiki/Fantasia_(1940...,2.28 M,76.4–83.3 M,126
3,The Reluctant Dragon,"June 20, 1941",https://en.m.wikipedia.org/wiki/The_Reluctant_...,"600,000","960,000",74
4,Dumbo,"October 23, 1941",https://en.m.wikipedia.org/wiki/Dumbo,"950,000",1.3 M,64

In [62]:
data["Box_office(USD)"]= data["Box_office(USD)"].str.replace("billion","B")

In [64]:
data.to_excel("cleaned_Disney_movies_r.xlsx")

In [60]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.8-py2.py3-none-any.whl (244 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.8